web/iosblog/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from . import adminsite
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^', include('x123.urls')),
    url(r'^admin/', adminsite.admin_site.urls),
]


# Login and logout views for the browsable API
urlpatterns += [
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/x123/urls.py
from django.conf.urls import url

from . import views
from . import restapi

app_name = 'x123'
urlpatterns = [
    # ex: /
    url(r'^$', views.index, name='index'),
    # ex: /d/1/
    url(r'^d/(?P<domain_id>[0-9]+)/$', views.domain, name='domain'),
    # ex: /a/1/
    url(r'^a/(?P<aspect_id>[0-9]+)/$', views.aspect, name='aspect'),

    # ex: /bookmark/5/
    url(r'^b/(?P<bookmark_id>[0-9]+)/$', views.bookmark, name='bookmark'),

    url(r'^api/domains/$', restapi.DomainList.as_view()),
    url(r'^api/angles/$', restapi.AngleList.as_view()),
    url(r'^api/bookmarks/$', restapi.BookmarkList.as_view()),
    url(r'^api/bookmarks/(?P<pk>[0-9]+)/$', restapi.BookmarkDetail.as_view()),

    url(r'^api/auth_info/$', restapi.auth_info),
    url(r'^api/bookmark_existed/$', restapi.bookmark_existed),
    url(r'^api/bookmark_save/$', restapi.bookmark_save),
    url(r'^api/bookmark_remove/$', restapi.bookmark_remove),
    url(r'^api/bookmark_click/$', restapi.bookmark_click),

    url(r'^api/bookmarks_in_aspect/(?P<aspect_id>[0-9]+)/$', restapi.BookmarkListInAspect.as_view()),
    url(r'^api/feeds/$', restapi.FeedList.as_view()),
]

web/x123/models.py
from django.db import models
from django.conf import settings


class Domain(models.Model):
    name = models.CharField('名称', max_length=100, unique=True)
    tag = models.CharField('Tag', max_length=10, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    zindex = models.IntegerField('排序参考值', default=0)
    description = models.TextField('描述', default='', blank=True, null=True)
    iconfont = models.CharField('IconFont', max_length=20, default='', blank=True)

    class Meta:
        verbose_name = '一级分类'
        verbose_name_plural = '一级分类'
        ordering = ['zindex']

    def aspects(self):
        return Aspect.objects.filter(domain_id=self.id).order_by('-zindex','id')

    def __str__(self):
        return self.name


class Aspect(models.Model):
    name = models.CharField('名称', max_length=100, unique=True)
    tag = models.CharField('Tag', max_length=10, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    domain = models.ForeignKey(Domain, verbose_name='一级分类', on_delete=models.CASCADE)
    zindex = models.IntegerField('排序参考值', default=0)
    description = models.TextField('描述', default='', blank=True, null=True)
    iconfont = models.CharField('IconFont', max_length=20, default='', blank=True)

    class Meta:
        verbose_name = '二级分类'
        verbose_name_plural = '二级分类'
        ordering = ['zindex']

    def __str__(self):
        return self.name


class Angle(models.Model):
    name = models.CharField('名称', max_length=100)
    tag = models.CharField('Tag', max_length=10, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    zindex = models.IntegerField('排序参考值', default=0)
    description = models.TextField('描述', default='', blank=True, null=True)
    iconfont = models.CharField('IconFont', max_length=20, default='', blank=True)

    class Meta:
        verbose_name = '视角'
        verbose_name_plural = '视角'
        ordering = ['zindex']

    def __str__(self):
        return self.name


# bookmark (the core data)
class Bookmark(models.Model):
    name = models.CharField('名称', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    aspect = models.ForeignKey(Aspect, verbose_name='二级分类', on_delete=models.CASCADE)
    angle = models.ForeignKey(Angle, verbose_name='视角', on_delete=models.CASCADE, null=True, blank=True)

    url = models.TextField('网址', max_length=1000)
    description = models.TextField('描述', max_length=2000, blank=True, null=True, default='')
    favicon = models.TextField(max_length=1000, blank=True, null=True)
    image = models.ImageField('截图', upload_to='screenshots', max_length=1000, blank=True, null=True)

    feed_url = models.TextField(max_length=1000, blank=True, null=True)
    feed_type = models.SmallIntegerField(default=0)

    clicks = models.BigIntegerField('点击次数', default=0)
    zindex = models.IntegerField('排序参考值', default=0)
    region = models.IntegerField('区域', default=0)

    creator = models.ForeignKey('auth.User', related_name='bookmarks')

    # 0 site , 1 article
    content_type = models.IntegerField(default=0)

    large_icon = models.ImageField('图标', upload_to='siteicons', null=True, blank=True)

    # parser name, default blank
    spider = models.TextField('爬虫', max_length=20, blank=True, default='')


    class Meta:
        verbose_name = '网址'
        verbose_name_plural = '网址'

    def __str__(self):
        return self.name

    def display_icon(self):
        if self.large_icon is not None and str(self.large_icon) != '':
            return settings.MEDIA_URL + str(self.large_icon)
        return str(self.favicon)

web/x123/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Domain, Aspect, Bookmark, Angle
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def fetch_paginator_bookmarks(request, bookmark_list):
    paginator = Paginator(bookmark_list, 56)
    page = request.GET.get('page')
    try:
        bookmarks = paginator.page(page)
    except PageNotAnInteger:
        bookmarks = paginator.page(1)
    except EmptyPage:
        bookmarks = paginator.page(paginator.num_pages)

    return bookmarks


def index(request):
    domains = Domain.objects.order_by('-zindex')
    angles = Angle.objects.order_by('-zindex')

    angle_id = request.GET.get('angle')
    if angle_id is None:
        bookmark_list = Bookmark.objects.order_by('-created_at')
    else:
        bookmark_list = Bookmark.objects.filter(angle_id=angle_id).order_by('-created_at')

    bookmarks = fetch_paginator_bookmarks(request, bookmark_list)

    return render(request, 'x123/index.html', {
        'domains': domains,
        'angles': angles,
        'bookmarks': bookmarks
    })


def domain(request, domain_id):
    domain = get_object_or_404(Domain, pk=domain_id)

    domains = Domain.objects.order_by('-zindex')
    angles = Angle.objects.order_by('-zindex')

    angle_id = request.GET.get('angle')
    if angle_id is None:
        bookmark_list = Bookmark.objects.filter(aspect__domain=domain_id).order_by('-created_at')
    else:
        bookmark_list = Bookmark.objects.filter(aspect__domain=domain_id, angle_id=angle_id).order_by('-created_at')

    bookmarks = fetch_paginator_bookmarks(request, bookmark_list)
    return render(request, 'x123/index.html', {
        'domain': domain,
        'domains': domains,
        'angles': angles,
        'bookmarks': bookmarks
    })


def aspect(request, aspect_id):
    aspect = get_object_or_404(Aspect, pk=aspect_id)

    domains = Domain.objects.order_by('-zindex')
    angles = Angle.objects.order_by('-zindex')

    angle_id = request.GET.get('angle')
    if angle_id is None:
        bookmark_list = Bookmark.objects.filter(aspect=aspect_id).order_by('-created_at')
    else:
        bookmark_list = Bookmark.objects.filter(aspect=aspect_id, angle_id=angle_id).order_by('-created_at')

    bookmarks = fetch_paginator_bookmarks(request, bookmark_list)

    return render(request, 'x123/index.html', {
        'aspect': aspect,
        'domains': domains,
        'angles': angles,
        'bookmarks': bookmarks
    })


def angle(request, angle_id):
    angle = get_object_or_404(Angle, pk=angle_id)

    domains = Domain.objects.order_by('-zindex')
    angles = Angle.objects.order_by('-zindex')
    bookmark_list = Bookmark.objects.filter(angle=angle_id).order_by('-created_at')
    bookmarks = fetch_paginator_bookmarks(request, bookmark_list)

    return render(request, 'x123/index.html', {
        'angle': angle,
        'domains': domains,
        'angles': angles,
        'bookmarks': bookmarks
    })


def bookmark(request, bookmark_id):
    bookmark = get_object_or_404(Bookmark, pk=bookmark_id)

    return render(request, 'x123/bookmark.html', {
        'bookmark': bookmark
    })

web/x123/templates/x123/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>番茄阅读 - 专注于精选 iOS/OS X 开发者博客</title>

    {% load staticfiles %}

    <script src="//cdn.bootcss.com/jquery/2.2.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.js"></script>
    <link href="//cdn.bootcss.com/semantic-ui/2.1.8/semantic.min.css" rel="stylesheet">

    <script src="{% static 'x123/js/common.js' %}"></script>
    <link href="{% static 'x123/style/common.css' %}" rel="stylesheet">

    <link href="{% static 'x123/image/favicon.png' %}" rel="icon"/>

    <script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?76ae24a848d4c14538f215644a9e13c1";
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(hm, s);
})();
</script>

</head>
<body>

<div class="ui stackable container menu">
    <div class="item">
        <img src="{% static 'x123/image/on.png' %}">
        番茄阅读 (iOS)
    </div>

    <a class="item" href="/">首页</a>

    {% for domain in domains %}
    {% for aspect in domain.aspects %}

    <a class="item" href="{% url 'x123:aspect' aspect.id %}">{{ aspect.name }}</a>

    {% endfor %}
    {% endfor %}
</div>


<div class="ui container">
  <div class="ui segments">
    <div class="ui segment">
        {% if bookmarks %}
            <div class="ui relaxed list">
                {% for bookmark in bookmarks %}
                    <div class="item">
                        <img class="ui mini image" src="{% if bookmark.favicon != '' %}{{ bookmark.favicon }} {% else %}{% static 'x123/image/def.png' %}{% endif %}">

                        <div class="content">
                            <a class="header" id="bookmark_link" bookmark_id="{{ bookmark.id }}" href="{{ bookmark.url }}" target="_blank">
                                {{ bookmark.name }}
                                {% if bookmark.feed_url != '' %}
                                    <img src="{% static 'x123/image/feed.png' %}">
                                {% endif %}
                            </a>
                            <div class="description">
                                {{ bookmark.description }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if bookmarks.paginator.num_pages > 1 %}
                    <div class="item">
                        <div class="ui pagination menu">
                            {% if bookmarks.has_previous %}
                                <a class="item" href="?page={{ bookmarks.previous_page_number }}">Previous</a>
                            {% endif %}
                            <a class="item">
                                <span class="current">
                                    Page {{ bookmarks.number }} of {{ bookmarks.paginator.num_pages }}.
                                </span>
                            </a>
                            {% if bookmarks.has_next %}
                                <a class="item" href="?page={{ bookmarks.next_page_number }}">Next</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            </div>
        {% else %}
            <p>No bookmarks</p>
        {% endif %}
    </div>
  </div>

  <div class="ui segment" align="center">
      <a href="http://everettjf.github.io/2016/02/24/iosblog-cc-dev-memory" target="_blank">关于iOS博客精选</a>
      &nbsp;&nbsp;
      <a href="https://github.com/everettjf/iOSBlog/issues/4" target="_blank">提交网址</a>
  </div>
</div>





</body>
</html>